[package]
name = "agon-light-emulator-debugger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.4.0"
ez80 = { git = "https://github.com/tomm/ez80.git", rev="feb4586b3541f2a1da6d45d69b6760851c0279f0"}
agon-cpu-emulator = { git = "https://github.com/tomm/agon-cpu-emulator.git", rev="15c09c531b9d72d916adc2bc5ef06a1a8e5008c5"}
#ez80 = { path = "../ez80" }
#agon-cpu-emulator = { path = "../agon-cpu-emulator" }
rustyline = "11.0.0"
