[package]
name = "agon-light-emulator-debugger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agon-cpu-emulator = { path = "../agon-cpu-emulator" }
ctrlc = "3.4.0"
ez80 = { git = "https://github.com/tomm/ez80.git", rev="f3598df34bfa1c2790f4ad041d4e06956447344a"}
#ez80 = { path = "../ez80" }
rustyline = "11.0.0"
