[package]
name = "agon-light-emulator-debugger"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.4.0"
agon-cpu-emulator = { git = "https://github.com/tomm/agon-cpu-emulator.git", rev="836a74b87a0750d0ffbfa8a0aa4b9e07aab45dd2"}
#agon-cpu-emulator = { path = "../agon-cpu-emulator" }
rustyline = "11.0.0"
