[package]
name = "agon-light-emulator-debugger"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.4.0"
agon-cpu-emulator = { git = "https://github.com/tomm/agon-cpu-emulator.git", rev="472ed569a2331ed4b76025bef6c5d6d760d9231f"}
#agon-cpu-emulator = { path = "../agon-cpu-emulator" }
rustyline = "11.0.0"
